name:                simple-bot
version:             0.1.0.0
github:              "qqoen/simple-bot"
license:             BSD3
author:              "qqoen"
maintainer:          "qqoenous@gmail.com"
copyright:           "2020 qqoen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/qqoen/simple-bot#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- text
- http-conduit
- lens
- lens-aeson 

library:
  source-dirs: src

executables:
  simple-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simple-bot

tests:
  simple-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simple-bot
